const CATEGORY_MAP = {
  roads: "roads",
  road: "roads",
  pothole: "roads",
  potholes: "roads",
  highway: "roads",
  street: "roads",
  pavement: "roads",
  sidewalk: "roads",
  water: "water",
  drainage: "water",
  sewage: "water",
  flooding: "water",
  leak: "water",
  pipe: "water",
  electricity: "electricity",
  electrical: "electricity",
  power: "electricity",
  streetlight: "electricity",
  lighting: "electricity",
  sanitation: "sanitation",
  garbage: "sanitation",
  waste: "sanitation",
  trash: "sanitation",
  cleanliness: "sanitation",
  "public-spaces": "public-spaces",
  park: "public-spaces",
  garden: "public-spaces",
  playground: "public-spaces",
  transportation: "transportation",
  transport: "transportation",
  traffic: "transportation",
  bus: "transportation",
  signal: "transportation",
  other: "other",
};

export function mapToCategory(value) {
  if (!value) return "other";
  const normalized = String(value).toLowerCase().trim();
  if (CATEGORY_MAP[normalized]) return CATEGORY_MAP[normalized];
  for (const [key, mapped] of Object.entries(CATEGORY_MAP)) {
    if (normalized.includes(key) || key.includes(normalized)) return mapped;
  }
  return "other";
}

export function parseConfidence(value) {
  if (typeof value === "number") return value;
  if (typeof value === "string") {
    const lower = value.toLowerCase();
    if (lower === "high" || lower === "very high") return 0.9;
    if (lower === "medium" || lower === "moderate") return 0.7;
    if (lower === "low") return 0.5;
    const parsed = parseFloat(value);
    if (!Number.isNaN(parsed)) return parsed > 1 ? parsed / 100 : parsed;
  }
  return 0.7;
}

export function parseAIResponse(text) {
  try {
    const cleanText = String(text || "").replace(/```json\s*/gi, "").replace(/```\s*/g, "").trim();
    const match = cleanText.match(/\{[\s\S]*\}/);
    if (!match) return null;
    const parsed = JSON.parse(match[0]);
    return {
      title: String(parsed.title || "").trim(),
      description: String(parsed.description || "").trim(),
      category: mapToCategory(parsed.category || "other"),
      confidence: parseConfidence(parsed.confidence || parsed.categoryConfidence),
      location: parsed.location ? String(parsed.location).trim() : null,
      duration: parsed.duration ? String(parsed.duration).trim() : undefined,
    };
  } catch {
    return null;
  }
}

export function fallbackResultFromText(userDescription = "", userLocation = "", hasImage = false) {
  const text = String(userDescription || "").trim();
  const lowered = text.toLowerCase();

  let category = "other";
  if (/(pothole|road|street|asphalt|crack)/.test(lowered)) category = "roads";
  else if (/(water|drain|sewage|leak|flood)/.test(lowered)) category = "water";
  else if (/(light|electric|power|wire|transformer)/.test(lowered)) category = "electricity";
  else if (/(garbage|trash|waste|dirty|sanitation)/.test(lowered)) category = "sanitation";
  else if (/(park|playground|public space|footpath|sidewalk)/.test(lowered)) category = "public-spaces";
  else if (/(traffic|bus|transport|signal|metro)/.test(lowered)) category = "transportation";

  const firstSentence = text.split(/[.!?]\s+/)[0]?.trim() || "Civic issue reported";
  const titleBase = firstSentence.length > 58 ? `${firstSentence.slice(0, 55)}...` : firstSentence;
  const title = titleBase || "Civic Issue Report";

  return {
    suggestedTitle: title,
    enhancedDescription: text || "Issue report submitted by citizen.",
    predictedCategory: category,
    categoryConfidence: text ? 0.62 : 0.5,
    isDuplicate: false,
    isSpam: false,
    spamScore: 0,
    imageQuality: hasImage ? "good" : "fair",
    imageQualityScore: hasImage ? 0.8 : 0.5,
    extractedLocation: userLocation
      ? { address: userLocation, lat: 0, lng: 0, confidence: 0.6 }
      : undefined,
    suggestedDuration: "1-2 weeks",
  };
}

export function toMlResult(parsed, hasImage) {
  return {
    suggestedTitle: parsed?.title || "Civic Issue Report",
    enhancedDescription: parsed?.description || "Issue analysis generated by AI.",
    predictedCategory: parsed?.category || "other",
    categoryConfidence: parsed?.confidence || 0.6,
    isDuplicate: false,
    isSpam: false,
    spamScore: 0,
    imageQuality: hasImage ? "good" : "fair",
    imageQualityScore: hasImage ? 0.8 : 0.5,
    extractedLocation: parsed?.location
      ? { address: parsed.location, lat: 0, lng: 0, confidence: 0.6 }
      : undefined,
    suggestedDuration: parsed?.duration,
  };
}

export async function imageUrlToDataUrl(imageUrl) {
  if (!imageUrl) return null;
  const response = await fetch(imageUrl);
  if (!response.ok) return null;
  const arrayBuffer = await response.arrayBuffer();
  const contentType = response.headers.get("content-type") || "image/jpeg";
  const base64 = Buffer.from(arrayBuffer).toString("base64");
  return `data:${contentType};base64,${base64}`;
}
